Args = --initialize-at-run-time=io.jsonwebtoken.impl.security.StandardSignatureAlgorithms \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.StandardEncryptionAlgorithms \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.StandardKeyOperations \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.StandardCurves \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.StandardKeyAlgorithms \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.StandardSecureDigestAlgorithms \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.DefaultAeadAlgorithm \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.DefaultHashAlgorithm \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.DefaultMacAlgorithm \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.DefaultRsaKeyAlgorithm \
       --initialize-at-run-time=io.jsonwebtoken.impl.security.DefaultSignatureAlgorithm \
       --initialize-at-run-time=io.jsonwebtoken.impl.DefaultJwtBuilder \
       --initialize-at-run-time=io.jsonwebtoken.impl.DefaultJwtParser \
       --initialize-at-run-time=io.jsonwebtoken.impl.DefaultJwtParserBuilder
