CREATE SEQUENCE seq_medias START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE seq_externals_references START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE seq_alternative_titles START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE seq_people START WITH 1 INCREMENT BY 50;

ALTER SEQUENCE seq_medias RESTART WITH 458830;
ALTER SEQUENCE seq_externals_references RESTART WITH 201324;
ALTER SEQUENCE seq_alternative_titles RESTART WITH 122752;

ALTER TABLE medias DROP INDEX idx_title;
ALTER TABLE medias DROP INDEX idx_name;
