ALTER TABLE `user_media_list`
    ADD COLUMN IF NOT EXISTS `rewatch_count` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `is_private` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `personal_notes` VARCHAR(2000) DEFAULT NULL;
