name: Generate and Publish Javadoc 📚

on:
  push:
    branches:
      - master # Dispara no merge ou push pro master

permissions:
  contents: write # Permissão para o bot commitar na branch gh-pages

jobs:
  publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout do repositório
        uses: actions/checkout@v4

      - name: ☕ Configurar Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Atualizado para o seu Java 21
          distribution: 'temurin'
          cache: 'gradle' # Cache mudou de maven para gradle!

      - name: 🔐 Dar permissão de execução para o gradlew
        run: chmod +x ./gradlew

      - name: 🛠️ Construir o Javadoc com Gradle
        # O Gradle gera a documentação na pasta build/docs/javadoc
        run: ./gradlew javadoc

      - name: 🚀 Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc # Caminho atualizado para o output do Gradle
          publish_branch: gh-pages
          commit_message: "docs: Atualização automática do Javadoc via GitHub Actions (Gradle) 🤖"
